### ISSUE TITLE
WB-Weather

### ISSUE THREAD

**Issue by kurtern84** [delightedCrow/WallberryTheme#1]
Hi,
Having problems with wb-weather. It starts and loads, but then nothing happens. No errors, and i know the api-key is working.

Here is my config:
{
			module: "WallberryTheme/WB-weather",
			position: "bottom_bar",  // Highly suggested location
			config: {
						// See "Configuration options" for more information.
						darkSkyApiKey: "***********",
						latitude: 60.6527370,
						longitude: 10.7404960
				}
		},

**Comment by kurtern84** [comment]
Forget it, i figured it out :)

**Comment by MichaelF1** [comment]
Oh man Help me out.I have the same error. At the beginning there is "Weather is loading" and then nothing happens- there is no weather data displayed. How did you fix that?

**Comment by kurtern84** [comment]
Include units in config.js. 
Like this:
{
			module: "WallberryTheme/WB-weather",
			position: "bottom_bar",  // Highly suggested location
			config: {
						// See "Configuration options" for more information.
						darkSkyApiKey: "58b961c402662db3104e806eb0d8710d",
						latitude: 60.6527370,
						longitude: 10.7404960,
						units: "si"
				}
		},

**Comment by delightedCrow** [comment]
I'm gonna re-open this because I could definitely use some better error messaging here. Thanks!

**Comment by MichaelF1** [comment]
allright, As i tried it without the units part with npm start dev there was only an error: 400, but i did not find something in your code. By the way you can add in your ReadMe that the unsplash collection id is found in the link of the wanted gallery on unsplash.com. Maybe you want to add it at the 3rd party page so you will get more views for that.

Thanks for this nice module.

**Comment by delightedCrow** [comment]
@MichaelF1 thanks, those are good suggestions!
