### ISSUE TITLE
New `fade` broken when not using WB-clock and WB-weather

### ISSUE THREAD

**Issue by weiserhei** [delightedCrow/WallberryTheme#10]
Hello,

do you want to support using `backgroundFade` for people who are not using the WB-Clock and WB-weather Modules?

Problem description:
The new Background Fade doesnt show up for me, because Im not using WB-clock or WB-weather. I havent customized anything special, its a default `MagicMirror` with some options tweaked. When I add some RSS feed in the `bottom_bar`-position, this results in rendering the fade only around this module, and not at the bottom in general:

![grafik](https://user-images.githubusercontent.com/7581732/52975561-4410be80-33c6-11e9-9b33-79e87a8e5287.png)

**Comment by delightedCrow** [comment]
oops, the fade was meant to work outside of WB-clock and weather. Thanks for the bug report!
