### ISSUE TITLE
Implement Unsplash search by queries

### ISSUE THREAD

**Issue by samusaran** [delightedCrow/WallberryTheme#11]
It would be nice to implement the `query` parameter for unsplash random photo API.

I was thinking about a trivial implementation of the `query` parameter that always filter for that specific term, or a more complex `queries` parameters that accepts multiple queries that are randomly selected each refresh.

Single query:
```
config: {
   query: "birds" // every search will be filtered by birds keyword
}
```
Multiple queries:
```
config: {
   // every search will be filtered by one of those keywords, randomly selected or cycled through in order
   queries: [ 
      "birds",
      "home",
      "sky"
   ]
}
```

It could be used instead or in conjunction with the `collections` parameter.

**Comment by delightedCrow** [comment]
a wonderful idea :)

**Comment by samusaran** [comment]
Do you accept pull requests? I should have a working implementation.

**Comment by delightedCrow** [comment]
Yep, I do accept pull requests and I've been meaning to put together a contributors doc. 

Your code looks great, do you mind adding a description for the `queries` option to the Configuration Options section in the [README.md](https://github.com/delightedCrow/WallberryTheme/blob/master/README.md) file and submitting the pull request to the dev branch? Thanks for the feature 👍

**Comment by delightedCrow** [comment]
Nice work!
