### ISSUE TITLE
Improve image attribution by including more details about the image

### ISSUE THREAD

**Issue by samusaran** [delightedCrow/WallberryTheme#13]
In those couple of days of use of your theme (so cool btw) I wondered a couple of times where the image were shot.

I would suggest to change the actual template from
```Photo by {author} on Unsplash```
to
```Shot by {author} in {city}, {country} on Unsplash```

Feel free to change the wording, I'm not a native english speaker so you may come up with a better phrasing. As the last time, I may pull request the change, as I've already tested on my setup.

**Comment by delightedCrow** [comment]
It's funny, I was thinking about this during implementation and part of the reason I didn’t include photo location was that I wasn’t sure how well it would translate into languages other than English, so I went with the  `Photo by {author} on Unsplash` which was suggested in the Unsplash documentation.

Originally I thought it might be neat to make this something customizable by the user, that they could enter a template string as a config option and any variables would be programmatically replaced with the corresponding Unsplash data, but I never did get around to implementing it. 

I think the only downside to using the data fields other than `author` is that not every photo reliably has all the data attributes filled in, which can give you weird output sometimes.

**Comment by samusaran** [comment]
I've made an implementation [here](https://github.com/delightedCrow/WallberryTheme/compare/dev...samusaran:dev) and I have handled the change of missing fields.

Basically the cases are:
- No location fields: nothing changes from the actual template
- Country only: `Shot by author in country`
- City only (actually never saw that): `Shot by author in city`
- City and country: `Shot by author in city, country`

I'm not proficient with nunjucks templates so I don't know how clean my solution is, but it seems to work fine right now.

**Comment by delightedCrow** [comment]
sorry about the long wait, all projects have gone on hiatus while I've been moving.

I think your solution looks good, you're welcome to make a PR to dev if you're still interested :)
