### ISSUE TITLE
WB-Weather exceeds 1000 calls on DarkSky API

### ISSUE THREAD

**Issue by nabbl** [delightedCrow/WallberryTheme#15]
Hello there,

The DarkSky API gets consumed a lot when having wb-weather online. It basically reaches 1000 calls in maybe an hour.

I tried to set updateInterval in the config.js to an hour (in milliseconds of course) but it has no effect at all.

Anyone knows how to change that?

**Comment by delightedCrow** [comment]
Whoa, that's a new one. Can you post your config.js and the version of MagicMirror you're running?

**Comment by LadnerJamie** [comment]
I am also having this issue today. I'm not sure why today and not other days. I have been alternating between two different config.js files to test which look I like better. My other config.js file does not use my darksky API. Within about 5 hours of using the config I've posted below I have exceeded my 1000 API calls.

There were a couple of things that I can think of that were different about my MM today using the following config.js. 1) I reloaded MM by using after changing the config.js using "pm2 reload mm" instead of just restarting MM. 2) I had a firefox window open on my PC with MM displayed on it.

I'll poke around at it again tomorrow, but if you'd like me to do any troubleshooting please let me know.

```
var config = 
{
	address: "",
	electronOptions: {
		
	},
	ipWhitelist: [
		
	],
	modules: [
  // Base WallberryTheme adds new font, styles, and a rotating background image pulled from Unsplash.com
  {
    module: "WallberryTheme",
    position: "fullscreen_below", // Required Position
    config: {
      unsplashAccessKey: "ef094357127c48684e9612b6510899bbb01f006167d3a100b5e9964e89062cb2", // REQUIRED
      collections: "3738678,3739143",	  // optional - leave empty for a random photo
	  updateInterval: 6000000
    }
  },
  // WB-clock adds local time (Optional Module)
  {
    module: "WallberryTheme/WB-clock",
    position: "top_bar", // highly suggest using top_bar position
    config: {
      timeFormat: "12",
	  localCityName: "Vancouver",	  // optional
      otherCities: [
      	{name: "Ireland", timezone: "Europe/Dublin"}, // optional
      	{name: "Anchorage", timezone: "US/Alaska"} // optional
      ]
    }
  },
  // WB-weather adds weather via DarkSky API (Optional Module)
  {
    module: "WallberryTheme/WB-weather",
    position: "bottom_bar",  // Highly suggested location
    config: {
      // See "Configuration options" for more information.
      darkSkyApiKey: "7b58887480152ba87ef4c3600d2f8943",	  // REQUIRED
      latitude:   49.090210, // REQUIRED
      longitude: -123.06526 // REQUIRED
    }
  },
  {
                module: 'MMM-ShairportMetadata',
                position: 'bottom_left',
                classes: "default",
                         config: {
                         metadataPipe: "/tmp/shairport-sync-metadata", // location of pipe with shairport-sync metadata
	                 alignment: "left",	// Possible values [left|right|center]. Default: center
                         }
        }
],
	paths: {
		modules: "modules",
		vendor: "vendor"
	}
}
```

**Comment by moos** [comment]
Ran into same issue.  Looks like the "newsfeed" module updates every 10 seconds and sends a
```
WB-weather received a module notification: NEWS_FEED from sender: newsfeed
```
which causes WB-weather to update the DOM and fetch the weather again.  Fix submitted.

**Comment by delightedCrow** [comment]
@moos ha, epic. I should finally have time to review and merge tomorrow - thanks for the contributions!

**Comment by delightedCrow** [comment]
I’ve done a huge amount of investigating for this issue and I still haven’t been able to reproduce any excessive API calls. After a good bit of review I don’t think any cross-talk from other modules sending notifications could be causing the issue.

My guess for the most likely scenarios that could cause this issue are: 

* Running multiple versions of WB-Weather concurrently in the same MagicMirror instance. Given the general feedback I’ve gotten here this probably wasn’t the issue for anyone, but better support for concurrent instances of WB-Weather will be coming in the next update just in case.
* Running multiple instances of MagicMirror + WB-Weather at a time. If you have multiple servers running the app and consuming the same DarkSky API and/or doing development work that causes a lot of refreshing, it’s actually quite easy to quickly to run out your 1000 calls a day before you realize it. I have had this happen to me before, and I think this is probably the most likely cause.
* Setting the `updateInterval`  value in the WB-Weather config too low, especially if this happens in conjunction with the case above. 

If anyone is still having this issue and can confirm it’s not related to the cases above, please do re-open the ticket and add your data.
