### ISSUE TITLE
Weather Showing Incorrect Dates

### ISSUE THREAD

**Issue by christinagilligan** [delightedCrow/WallberryTheme#16]
On my weather module, I have it showing four days into the future. The issue is is that "today" is repeated! For example, if it's Friday, my four days show up as Today, Friday, Saturday, Sunday even though today is Friday. Not too sure what's causing it yet.

**Comment by delightedCrow** [comment]
thanks for the bug report. Is this issue persistent when you reboot magic mirror? Can you also post your config.js file (with api keys redacted)?

**Comment by christinagilligan** [comment]
Well I just checked what was going on with it and it seems to be working right now. Maybe it just hadn't updated to my location's time properly? Not sure but I'll close this!
