### ISSUE TITLE
Blank screen after installing Wallberry Theme

### ISSUE THREAD

**Issue by nightraven16** [delightedCrow/WallberryTheme#17]
![Snippet](https://user-images.githubusercontent.com/19562327/64496285-62121380-d271-11e9-8ebb-229ccee5391b.png)
Not sure why but after I put the wallberry Theme folder in the modules dir and insert the jave script into the config.js file then I reboot and all I get is a blank screen after magic mirror loads. If I remove the script the default loads just fine. my script is below.

modules: [
  // Base WallberryTheme adds new font, styles, and a rotating background image pulled from Unsplash.com
  {
    module: "WallberryTheme",
    position: "fullscreen_below", // Required Position
    config: {
      unsplashAccessKey: "XXX", // REQUIRED
      collections: "217461",
      autoDimOn: false
    }
  },
  // WB-clock adds local time (Optional Module)
  {
    module: "WallberryTheme/WB-clock",
    position: "top_bar", // highly suggest using top_bar position
    config: {
      localCityName: "Seattle", // optional
      otherCities: [
      	{name: "DC", timezone: "US/Eastern"}, // optional
      	{name: "Anchorage", timezone: "US/Alaska"} // optional
      ]
    }
  },
  // WB-weather adds weather via DarkSky API (Optional Module)
  {
    module: "WallberryTheme/WB-weather",
    position: "bottom_bar",  // Highly suggested location
    config: {
      // See "Configuration options" for more information.
      darkSkyApiKey: "Your DarkSky API key", // REQUIRED
      latitude:   47.603230, // REQUIRED
      longitude: -122.330276 // REQUIRED
    }
  }
]

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by delightedCrow** [comment]
The most common cause for the blank screen that I can think of is a syntax error in your config.js script (you can use `npm run config:check` from the command line in your MagicMirror directory to check your config file for errors).
If your config.js isn't giving you any errors, can you check to see if there are any errors showing up in the browser's developer console?

**Comment by nightraven16** [comment]
Thanks @delightedCrow I was missing a }, issue resolved
