### ISSUE TITLE
API calls very high during startup

### ISSUE THREAD

**Issue by roccodicarlo** [delightedCrow/WallberryTheme#22]
Similar to issue number 1, I am seeing a huge spike in API calls to unsplash only during startup, or refresh or restart MM.

I have 7 Wallberry modules configured, since I am using Pages.  Each Page has a different collection or module associated with it.  I have set the update interval to be 1hour, and I have persistance enabled in my PAGE-SELECTOR module.  

Unsplash limits us to 50 requests/hour, and what I am observing is during startup, Typically 6-8 requests are made per Walberry module.  For 7 modules, I exceed the 50 and must wait for the next hour to have the API interface reset.  When you start up, is the module doing a lot of queries before downloading?  

Everything still works, but I wanted to see if you can optimize (minimize) the start-up API calls.

**Comment by delightedCrow** [comment]
This sounds like it's probably an issue with the way your Pages module manages the different WallberryTheme module instances, as WallberryTheme makes only one API request on start up or on resume. Without knowing how the Pages module works, I'm not sure what would cause the multiple requests - it sounds like something the Pages module is doing is causing each WallberryTheme instance to be started or refreshed multiple times.

This probably isn't something I can fix cleanly on my end. WallberryTheme does currently support wake and resume notifications so other modules can order WallberryTheme to suspend API requests while in the background, but it's up to them to do so.

You can post a link to the Pages module you're using and it's possible there will be something we can do to help integrate WallberryTheme with it, but without knowing how the other module works I can't be sure.
