### ISSUE TITLE
DarkSky API key 

### ISSUE THREAD

**Issue by usafle** [delightedCrow/WallberryTheme#23]
Any plans to change the Weather API calls to something else since Apple bought DarkSky and aren't offering API keys any longer?

**Comment by delightedCrow** [comment]
Yep. I haven’t settled on another default provider yet, but for a while now I’ve been mulling over an overhaul of WB-weather to make it more modular and able to accept multiple weather providers. Apple’s acquisition has certainly made that the priority for the next release.

Once I get around to my next ticket clean up I’ll be creating an issue for choosing/implementing a new default weather provider for WB-Weather, but if you want to leave comments or suggestions for a specific provider feel free to leave them here for now :)

**Comment by usafle** [comment]
Thanks. I've finally made the switch over from DakBoard to the actual MM2 software and was looking for something to change the MM2 display to look more like the DakBoard.  Your module had it all - except for the darksky weather issue.

I'll be watching this closely.  Thanks, ahead of time.

**Comment by arcangeloerrico** [comment]
Any update?

**Comment by delightedCrow** [comment]
@arcangeloerrico You can subscribe to #24 for updates on this. I've finally had some time to work on this over the last week and unless some new disaster strikes I might even have the new version pushed to the dev branch some time this weekend :)

**Comment by usafle** [comment]
@delightedCrow That's great news.
