### ISSUE TITLE
Refactor WB-Weather Module & Replace DarkSky as the default Weather Provider

### ISSUE THREAD

**Issue by delightedCrow** [delightedCrow/WallberryTheme#24]
Since [Apple has acquired DarkSky](https://blog.darksky.net/) and will be shutting down the service to 3rd parties next summer (good night sweet prince), it's time to choose a new weather provider for the WB-Weather module.

This would also be a great time to look into refactoring WB-Weather so that it's modular enough to handle choosing from multiple weather providers to supply weather data.

**Comment by usafle** [comment]
I'm also waiting on this as well

**Comment by android9pie2** [comment]
I'm waiting on this too. Shame that Apple acquired Dark Sky.

**Comment by stopspazzing** [comment]
Curious, why not just use some of the code from default weather module (not current weather or forecast) as it already supports multiple providers?

**Comment by saabman** [comment]
Ive just changed mine over to use the Australian Bureau of Meterology. Only suitable for Australian weather data. Unfortunately the BOM doesn't present their data in a nice tidy format like Darksky etc so it too a lot of rework to get it to work so I have made it a stand alone module. Im just tyding up the config and documentation and will release it hopefully later this week. My initial hack of the WB-weather module is here https://github.com/saabman/WallberryTheme This is just my first experimental attempt at NodeJS

**Comment by delightedCrow** [comment]
I wanna say I’ll have a chance to work on this soon but last time I thought that I caught covid and now the entire west coast of the US is burning down so… \*crosses fingers 2020 will chill for a bit\*

@stopspazzing I was hoping to use much of the code from the default weather module - the one issue that made integrating it less than straightforward was a quirk of how DarkSky structured their API and how the default weather module handled making requests. DarkSky required get requests to come from a proxy server which WB-Weather handled out-of-the-box by using the node_helper server to make the requests, whereas the default weather module requires a user to set up a separate proxy service for their module to contact which was a bit cumbersome, especially for novice MM users. I wanted to retain WB-Weather’s method at least for the duration of DarkSky support (though it's mostly a moot point now since it’s taken me so long to get around to this lol). I figured it might be worth checking to see if any other major weather providers had any similar requirements to make it worth modifying the default weather module’s code to be used by node_helper.

@saabman awesome nice work :)

**Comment by delightedCrow** [comment]
The functionality has now been added in 3.0.0. Thanks to everyone who showed their interest on this issue, and also for waiting patently for it through a very weird year :)
