### ISSUE TITLE
Possible memory leak/hang on the electron side

### ISSUE THREAD

**Issue by bjj** [delightedCrow/WallberryTheme#25]
The line `let img = document.createElement("img");` creates a new `img` every time an image is loaded. As far as I can tell, in the current version of MM, the page is never fully reloaded, so those elements just grow and grow. In my experience, WallberryTheme on an rpi3 (I'm using magicmirroros) will stop updating images after several hours at the fastest image update rate (50/hr limited by Unsplash API). I've verified that it's not API limits, and restarting the container (which restarts electron) always fixes it.

(I was using WallberryTheme/Unsplash as a placeholder while working on my own background plugin and I can hang the browser much faster doing the same thing because I have no rate limit. I fixed it by creating one `img` as `this.img` and re-using it.)

**Comment by delightedCrow** [comment]
Awesome, thanks for the report

**Comment by samusaran** [comment]
I had so many problems because of this. If I get some free time, I might try to address this issue.

Thanks for the specific report.

**Comment by delightedCrow** [comment]
Fixed by @samusaran in PR #28 (4e1324b3b152536dbc58a050b287670a0c87d967).
