### ISSUE TITLE
Unsplash showing wrong images

### ISSUE THREAD

**Issue by chill-gh** [delightedCrow/WallberryTheme#26]
This past week the background images have started showing random unsplash images from outside my collection. I confirmed my account and api key are still active on unsplash, updated electron, and checked for errors when running npm start dev (none found). Wondering if there's an API issue or a change that's causing it. I tried the api url and was getting random images from that too.

https://api.unsplash.com/photos/random?client_id=[mykey]&collections=3566656&orientation=portrait

**Comment by dorton** [comment]
Looks like an Unsplash API error. Private collections are being returned as 404. Take a look here `https://api.unsplash.com/users/:USERNAME/collections?client_id=:CLIENTID` and see if your collection is listed in the array. I had one that was doing the same thing. I created another public collection, added photos and now things seem to be working as expected.

**Comment by chill-gh** [comment]
Thanks @dorton, looks like that's what was needed. Not sure if Unsplash is having some issues or what, but it took a bit of work to get a new collection made and it wouldn't let me edit my existing collection to just make it public instead of private.
