### ISSUE TITLE
No image loading unless - clearCacheOnStart: false

### ISSUE THREAD

**Issue by Moerup** [delightedCrow/WallberryTheme#29]
**Describe the bug**
No image will load for me if the clearCacheOnStart is set to true.
If I set it to false, it loads correctly
No errors in log or dev tools.

````javascript
var config = {
    address: "localhost",
    port: 8080,
    basePath: "/",
    ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],

    useHttps: false,
    httpsPrivateKey: "",
    httpsCertificate: "",

    language: "en",
    logLevel: ["INFO", "LOG", "WARN", "ERROR", "DEBUG"],
    timeFormat: 24,
    units: "metric",

    modules: [{
            module: "WallberryTheme",
            position: "fullscreen_below",
            config: {
                unsplashAccessKey: "XXX",
                collections: "45585351",
                clearCacheOnStart: false,
            }
        }, {
            module: "WallberryTheme/WB-clock",
            position: "top_bar",
            config: {}
        }, {
            module: "WallberryTheme/WB-weather",
            position: "bottom_bar",
            config: {
                apiKey: "XXX",
                providerName: "openweathermap",
                latitude: 55.7974140,
                longitude: 9.694617
            }
        }, {
            module: "calendar",
            position: "top_right",
            disabled: true,
            config: {
                maximumEntries: 10000,
                colored: true,
                coloredSymbolOnly: false,
                calendars: [{
                        url: 'XXX',
                        color: '#263261',
                    },
                ],
            }
        }, {
            module: "MMM-MonthlyCalendar",
            position: "bottom_bar",
            config: {
                mode: "nextFourWeeks",
            }
        },
    ]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {
    module.exports = config;
}
````

Brand new setup of Magic Mirror on a Pi 4 2GB
Let me know if you need anything else!
Based on one of the other issues #8  I think it would be better to clear the cache, but atm it only works if that's disabled.

**Comment by scuppasteve** [comment]
> **Describe the bug**
> No image will load for me if the clearCacheOnStart is set to true.
> If I set it to false, it loads correctly
> No errors in log or dev tools.

I just installed on a RPi4 4gb and had the exact same issue, except i didnt have clear cache in at all, this actually fixed it for me. Thanks for the help. But i agree i would think you would want it to clear.

**Comment by delightedCrow** [comment]
This is an excellent report, thank you. I ordered a Rpi4 not too long ago so I will investigate this soon :)

**Comment by Moerup** [comment]
Sounds good, thanks a bunch for all the effort you have put into this. 
Really enjoying the look of it, it's soon going up on the wall!

**Comment by Moerup** [comment]
I just updated the module on my pi with the 2 latest commits you did (fast help!) and the background wouldn't show with clearCacheOnStart: false, after I set it to true it showed up immediately.
Seems like you fixed it 👍

**Comment by delightedCrow** [comment]
Awesome, thanks for the confirmation and for your help submitting the reports.
