### ISSUE TITLE
Weather Module

### ISSUE THREAD

**Issue by Robvred** [delightedCrow/WallberryTheme#33]
**Describe the bug**
Default config description for weather module is wrong. DarkSky API not anymore supported.

`darkSkyApiKey: "Your openweathermap API key", // REQUIRED`

**Error Messages**
Authorization Error

**Solution**
Replace `darkSkyApiKey: "Your openweathermap API key"` by `apiKey: "Your openweathermap API key"` in the config/config.js file.

**Comment by delightedCrow** [comment]
Ah, I see, the documentation for the config in the main [ WallberryTheme README.md](https://github.com/delightedCrow/WallberryTheme/blob/master/README.md#using-the-module) is outdated (uses the old `darkSkyApiKey` option) and should be updated to be the same as the [WB-weather README.md](https://github.com/delightedCrow/WallberryTheme/blob/master/WB-weather/README.md) (which uses the new `apiKey` option).

[DarkSky API is currently supported though](https://github.com/delightedCrow/WallberryTheme/blob/master/WB-weather/README.md#darksky), at least until Apple turns it off later this year :)
