### ISSUE TITLE
Background image not loading

### ISSUE THREAD

**Issue by nagree** [delightedCrow/WallberryTheme#35]
The background on my screen isn't loading, it keeps said "Loading background photo". The problem just occured yesterday, before that the background loaded normally. 

I've checked the dev tools, it show 1 warning about the Electron privacy and one error for another module. I've also deleted all files in the cache folder, but can't fix the problem. 

Anyone solved this problem before? Please let me know. Thank you.

**Comment by TheyFoundMe** [comment]
same here

**Comment by delightedCrow** [comment]
Thanks for the report - apparently [Unsplash has changed how their API handles parameters for image sizes](https://changelog.unsplash.com/2019/03/19/image-resizing.html) which is breaking WallberryTheme's image processing (and yesterday was the day they dropped support for the old API). 

Setting the option `resizeForScreen: false` in your config.js should make images display again (though they probably won't be sized to your screen appropriately). I should have a fix soon that uses Unsplash's new API.

**Comment by nagree** [comment]
thank you for the patch, it worked!

**Comment by delightedCrow** [comment]
Excellent, thank you for the report and the confirmation 👍
