### ISSUE TITLE
language in wb-weather

### ISSUE THREAD

**Issue by DanielWeeber** [delightedCrow/WallberryTheme#36]
Although I've selected "language: de" in the config, the weather is described in english.
esp. "overcast clouds".

"today" or similar is displayed in german though.
<img width="1762" alt="Bildschirmfoto 2021-03-04 um 22 33 13" src="https://user-images.githubusercontent.com/2935130/110033403-9fa60e80-7d39-11eb-8eaf-3bc54be70df8.png">

**Comment by delightedCrow** [comment]
Thank you for the report, this will be fixed soon.
