### ISSUE TITLE
Loading photo still remaining after the fix

### ISSUE THREAD

**Issue by anukra** [delightedCrow/WallberryTheme#38]
Sorry but i have update the module, but nothing change. I try to play with the option but nothing change. 

resizeForScreen true/false 
imagewidth/Height auto or pixel 
imageOptions fill or crop 

I'm out of idea . Thanks

**Comment by delightedCrow** [comment]
Please post your config.js. Are you getting any errors in the developer console?

**Comment by anukra** [comment]
Well, actually experienced a EADDRINUSE error . Maybe it' the fault. i'll try to solve it and then feedback. thanks for reply

**Comment by delightedCrow** [comment]
Oh, yeah, that’s a system error not a WallberryTheme error. It means the IP/port combo MagicMirror is trying to use is already in use (check if you’ve got another service running on that port/IP, or you can try rebooting).

**Comment by anukra** [comment]
`/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */


var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "it",
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default 
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device
	
	modules: [
			{
			module: "alert",
		},

		{
			module: "updatenotification",
			position: "top_bar"
		},
{
    module: 'MMM-SmartTouch',
    position: 'bottom_center',    // This can be any of the regions.(bottom-center Recommended)
    config: {
        // The config property is optional.
    	}
},

{
  module: 'MMM-CalendarExt2',
  config: {
    calendars : [
      {

        url: "https://calendar.google.com/calendar/ical/calendariovitali%40gmail.com/private-**************************************/basic.ics",
	name:"Famiglia",
	scanInterval: 1000*60*30,
	beforeDays: 60,
	afterDays: 365,
      },
    ],
    views: [
      {	
	name:"Famiglia",
        calendars:["Famiglia"],
	mode: "weekly",
	locale:"it-IT",
	slotMaxHeight:"300px",
      },
    ],
    scenes: [
      {
        name: "Famiglia",
	views:[],
      },
    ],
  },
},

	{
	  module:"MMM-CalendarExtMinimonth",
  	position:"top_right",
	source: "CALEXT2",	
	},

  {
    	module: "WallberryTheme",
   	position: "fullscreen_below", // Required Position
     	config: {
      		unsplashAccessKey: "********************************************************************", // REQUIRED
      		collections: "**********" // optional - leave empty for a random photo
         }
  },

		{
			module: "clock",
			position: "top_left"
		},
	
	
			
	{
   	 module: "WallberryTheme/WB-weather",
    	position: "bottom_bar",  // Highly suggested location 
   	 config: {
    	 	// See "Configuration options" for more information.
    		darkSkyApiKey: "9516a761aeb6e1267f0f64d0203f06cd", // REQUIRED
      		latitude:   43.7329200, // REQUIRED
     		longitude: 10.7974900 // REQUIRED
    }
},	


{
		module: "MMM-WeatherDependentClothes",
		position: "bottom_left",
		config: {
			// See 'Configuration options' for more information.
			location: "Firenze,Italia",
			locationID: "3176959", //Location ID from http://bulk.openweathermap.org/sample/city.list.json.gz
			appid: "************************" //openweathermap.org API key.
			},


	},
	

]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
`

**Comment by anukra** [comment]
`/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */
var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],
	language: "it",
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default 
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device	
	modules: [
			{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
{
    module: 'MMM-SmartTouch',
    position: 'bottom_center',    // This can be any of the regions.(bottom-center Recommended)
    config: {
        // The config property is optional.
    	}
},
{
  module: 'MMM-CalendarExt2',
  config: {
    calendars : [
      {
        url: "https://calendar.google.com/calendar/ical/calendariovitali%40gmail.com/private-*************************************/basic.ics",
	name:"Famiglia",
	scanInterval: 1000*60*30,
	beforeDays: 60,
	afterDays: 365,
      },
    ],
    views: [
      {	
	name:"Famiglia",
        calendars:["Famiglia"],
	mode: "weekly",
	locale:"it-IT",
	slotMaxHeight:"300px",
      },
    ],
    scenes: [
      {
        name: "Famiglia",
	views:[],
      },
    ],
  },
},
	{
	  module:"MMM-CalendarExtMinimonth",
  	position:"top_right",
	source: "CALEXT2",	
	},
  {
    	module: "WallberryTheme",
   	position: "fullscreen_below", // Required Position
     	config: {
      		unsplashAccessKey: "************************************************************************", // REQUIRED
      		collections: "9463324" // optional - leave empty for a random photo
         }
  },
		{
			module: "clock",
			position: "top_left"
		},		
	{
   	 module: "WallberryTheme/WB-weather",
    	position: "bottom_bar",  // Highly suggested location 
   	 config: {
    	 	// See "Configuration options" for more information.
    		darkSkyApiKey: "************************************", // REQUIRED
      		latitude:   43.7329200, // REQUIRED
     		longitude: 10.7974900 // REQUIRED
    }
},	
{
		module: "MMM-WeatherDependentClothes",
		position: "bottom_left",
		config: {
			// See 'Configuration options' for more information.
			location: "Firenze,Italia",
			locationID: "3176959", //Location ID from http://bulk.openweathermap.org/sample/city.list.json.gz
			appid: "***************************" //openweathermap.org API key.
			},
	},
]
};
/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
`

**Comment by anukra** [comment]
That my config file. In dev mode everything is loaded and any error is display.

**Comment by anukra** [comment]
Ok, sorry for the trouble a rough approach resolve it. Unistall everything and reinstall carefully. Thanks for your support

**Comment by delightedCrow** [comment]
glad you got it working 👍
