### ISSUE TITLE
No errors, but implementation is off in my use case

### ISSUE THREAD

**Issue by palominovet** [delightedCrow/WallberryTheme#46]
No errors are given, however, I keep getting a black strip along the right side of the screen - I have tried setting the Image height and width but it simply doesn't work, image is pushed off the left side of the screen by maybe... 30-40 pixels?
Also right before the images change, they go dim which is quite disconcerting.  Not sure how to change that.  Autodim on/off doesn't work.  Otherwise I love this module and am so thankful for it and the well written documentation.

**Comment by delightedCrow** [comment]
Thanks for using WallberryTheme :)

The dimming right before images change is probably related to the fadeout/fadein animation that happens as the images change. There isn't currently a setting to turn this animation on or off, but it is something I've considered adding before.

As for the image being pushed off the screen, it's hard to tell what could be causing this without a screen shot or seeing your config.js.
