### ISSUE TITLE
Be able to dim background photo

### ISSUE THREAD

**Issue by delightedCrow** [delightedCrow/WallberryTheme#7]
It would be nice to have an opacity option to dim the background photo. Might also be nice to be able to have an option to independently change the text brightness.

**Comment by weiserhei** [comment]
Just installed this nice Theme. I have a lot of Text on my screen, so I am looking for a solution to this also. The first thing that came into my mind is applying CSS Filters:

> MagicMirror/css/custom.css
```
.WallberryTheme img {
    filter: blur(4px) opacity(0.8);
}
```` 
Default:
![grafik](https://user-images.githubusercontent.com/7581732/52375854-f6f52a00-2a60-11e9-9058-56dc354dc22e.png)
Using Filter:
![grafik](https://user-images.githubusercontent.com/7581732/52375088-1723e980-2a5f-11e9-9aa1-12bb89114332.png)

Additionally you can add opacity to Modules to give them more contrast. Doing it like this is an insult to the beautiful aesthetics of the default wallberry theme, so be careful tho 🎃 
> MagicMirror/css/custom.css
```
.calendar, .newsfeed {
    background: rgba(34,34,34,0.75);
    padding:10px;
}
```

**Comment by delightedCrow** [comment]
Thanks, I love seeing others' mirror setups and thoughts! I'm really fond of the blur effect too, it's a classy solution.
This is a fun problem since (like you mentioned) it's easy to overdo an effect and have it muddy the theme or have it clash with other modules' aesthetics. Hopefully I can add a couple of options that look good in most cases but that are also easy to customize, we'll see 😄

**Comment by delightedCrow** [comment]
Latest version now allows a couple different options for dimming background images
